# Provided here are several examples that can be used to test the API that it is functioning correctly when running on the localhost.
#
# To make use of this file, you can use the REST Client extension for Visual Studio Code:
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client

###########################
# Swagger/Swashbuckle Test
# =========================
GET http://localhost:5000/swagger

####
# Example GET sending the text "SomeTextToEncode" - ANONYMOUS ACCESS
GET http://localhost:5000/api/encode?text=SomeTextToEncode&size=150

####
# Example POST sending a URL via post - ANONYMOUS ACCESS
POST http://localhost:5000/api/encode?size=500
Content-Type: text/plain

https://github.com/joelbyford/QrCodeApiApp


####
# Example GET sending the text "SomeTextToEncode" - BASIC AUTHENTICATION 
GET http://localhost:5000/api/encode?text=SomeTextToEncode&size=150
Authorization: Basic testUser:testPassword

####
# Example POST sending a URL via post - BASIC AUTHENTICATION
POST http://localhost:5000/api/encode?size=500
Content-Type: text/plain
Authorization: Basic testUser:testPassword

https://github.com/joelbyford/QrCodeApiApp