# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger: none

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/QrCodeApiApp.csproj'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/QrCodeApiApp.csproj'
    arguments: '--configuration $(buildConfiguration) --no-restore'
- task: WhiteSource Bolt@19
  inputs:
    cwd: '/'