name: Deploy on Push to Main
# only run on push to main (merges)
on:
  push:
    branches: [ main ]

# This workflow/action uses the Azure CLI to publish the webapp to a staging slot
# then tests the app to ensure the app is functioning in that staging slot
# If successfull, the workflow continues on and does a slot-swap.
# Since slot swap doesn't not yet have an action, it must be done via CLI
# so the whole workflow uses the CLI for consistency.
# See the *_test.yml for how to do azure webapp publish via action & publish profile instead.

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Setup dotnet 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore package dependencies
      run: dotnet restore

    - name: dotet build
      run: dotnet build --no-restore --configuration Release
      
    - name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp 
    
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: false
        # Name of the environment. Supported values are azurecloud, azurestack, azureusgovernment, azurechinacloud, azuregermancloud. Default being azurecloud
        environment: azureusgovernment
    
    - name: Azure Publish to Staging
      run: az webapp deploy --name ${{secrets.APP_NAME}} --resource-group ${{secrets.APP_RG}} --src-path ${{env.DOTNET_ROOT}}/myapp --slot staging --type zip

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v2.2.1

      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install requests
      - name: Test with pytest
        run: |
          cd QrCodeApiApp/test
          pytest --url ${{secrets.STAGING_URL}}
    
  swap-to-prod:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: false
          # Name of the environment. Supported values are azurecloud, azurestack, azureusgovernment, azurechinacloud, azuregermancloud. Default being azurecloud
          environment: azureusgovernment

      - name: Azure Publish to Staging
        uses: Azure/cli@1.0.4
        with:
          # Specify the script here
          inlineScript: az webapp deployment slot swap  --name ${{secrets.APP_NAME}} --resource-group ${{secrets.APP_RG}} --slot staging --target-slot production
          
          





