name: .NET Core - Release from Master
#
# Run when pushed to master (successfull PR with branch permissions turned on)
#
on: 
  push:
    branches: master

env:
  AZURE_WEBAPP_NAME: qrcode-api-app    # set this to your application's name

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Login to Azure
      run: dotnet build --configuration Release
    
    - name: dotnet publish
      run: |
          echo "Logging into Azure..."
          az login --service-principal -u ${{ secrets.CLIENT_ID }} -p ${{ secrets.CLIENT_SECRET }} --tenant ${{ secrets.TENANT_ID }}
        
    - name: 'Perform an az cli appservice slotswap'
      run: |
        echo "Running a CLI Slot Swap..."
        az webapp deployment slot swap --name qrcode-api-app --resource-group rgDoNotDeleteDemos --slot test --target-slot Production  
